codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 60%

ignore:
  - "experiments/**"
  - "tests/**"
  - "**/conftest.py"
  - "untextre/__main__.py"
  - "run_web_interface.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
